version: '2.2'
services:

  kafka-cluster:
    container_name: kafka-cluster
    image: landoop/fast-data-dev:2.3.0
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
      CONNECTORS: debezium-mysql,s3,debezium-postgres
      AWS_ACCESS_KEY_ID: "AKIAQUOMZI4GDEYLRZVL"
      AWS_SECRET_ACCESS_KEY: "k0Qqy+2TS1U/NjgbxzMC1AYCyTeIIgddh1i5OvGU"
      SAMPLEDATA: 0
    ports:
      - 2181:2181                   # Zookeeper
      - 3030:3030                   # Landoop UI
      - 8081-8083:8081-8083         # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585         # JMX Ports
      - 9092:9092                   # Kafka Broker
    volumes:
      - ./target/plugin/:/connectors/
    links:
      - mysql
      - aws-s3

  postgres:

    image: debezium/postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  mysql:
    build:
      context: src_mysql
    ports:
     - 3305:3306
    environment:
     - MYSQL_ROOT_PASSWORD=admin123
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw

  aws-s3:
    image: localstack/localstack:0.8.8
    container_name: aws-s3
    environment:
      SERVICES : s3:5000
      HOSTNAME : aws-s3
      AWS_ACCESS_KEY_ID : "AKIAQUOMZI4GDEYLRZVL"
      AWS_SECRET_ACCESS_KEY : "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"
    ports:
      - "5000:5000"
